# Generated by Django 2.2.12 on 2020-04-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_activityperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Online'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Username'),
        ),
    ]
